changed surpath community to surpath hub
SurPathHub/SurPathHub.github.io pull request #25
Opened 2021-04-18 18:19 UTC by bunnyrockz

2021-04-19 01:05 UTC, vinzvinci commented on index.html
>                      <p class="about__text">SurPath is an welcoming and inclusive open source community that helps every aspiring student or career shifter in the Philippines. We are here to learn, ge
Can you add **Hub** next to SurPath

2021-04-19 01:07 UTC, vinzvinci requested changes
Can you also add **Hub** in the footer.

Ex. 
`© 2021 SurPath. All right reserved`

2021-04-22 09:21 UTC, bunnyrockz commented on index.html
>                      <p class="about__text">SurPath is an welcoming and inclusive open source community that helps every aspiring student or career shifter in the Philippines. We are here to learn, ge
sure

2021-04-22 10:18 UTC, vinzvinci approved these changes
Looks good to me, I'll do the rest.

2021-04-22 10:19 UTC, merged